#!/bin/bash
session=`cat "$(dirname $0)/.session"`
if [[ "$1" == '-d' ]]; then
    day="$2"
    shift 2
fi
if [[ -z "$day" ]]; then
    echo "Day is required"
    exit 1
fi
output="$1"
if [[ -z "$output" ]]; then
    echo "Output directory is required"
    exit 1
fi

curl -s "http://adventofcode.com/2017/day/$day/input" -H "Cookie: session=$session" -o "$1/input"
